version: "3"
services:
  pastagan_plusplus_dev:
    image: pasta-gan-plusplus:0.0.1
    container_name: pastagan_plusplus_dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_NAME=$USER
        - USER_ID=$USER_ID
    runtime: nvidia
    shm_size: "8gb"
    ulimits:
      memlock: -1
      stack: 67108864
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ../pasta-gan-plusplus/:$HOME/Projects/pastagan/
    environment:
      - DISPLAY=$DISPLAY
    working_dir: $HOME/Projects/pastagan/
    network_mode: "host"
    restart: always
    tty: true
