version: "3"
services:
  pastagan_pp_test:
    image: pastagan_plus_plus:0.0.1
    container_name: pastagan_plus_plus
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_NAME=$USER
        - USER_ID=$USER_ID
    runtime: nvidia
    shm_size: "8gb"
    ulimits:
      memlock: -1
      stack: 67108864
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    privileged: true
    volumes:
      - ../pasta-gan-plusplus/:$HOME/Projects/pastagan/
      - ../UPT_512_320/:$HOME/Projects/datasets/
      - ../graphonomy/:$HOME/Projects/graphonomy/
      - ../openpose/:$HOME/Projects/openpose/
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    environment:
      - DISPLAY=$DISPLAY
    working_dir: $HOME/Projects/
    network_mode: "host"
    #restart: always
    tty: true
